name: project-name
recipe: wordpress

config:
    webroot: .
    php: "8.2"
    via: nginx # nginx / apache
    database: mysql # mysql / mariadb
    xdebug: true
    composer: true
    env_file:
        - .env
    # config:
    #     php: config/php.ini

services:
    node:
        type: node:22
    pma:
        type: phpmyadmin
        hosts:
            - database
    mailhog:
        type: mailhog
        hogfrom:
            - appserver

proxy:
    mailhog:
        - mail.project-name.lndo.site
    pma:
        - pma.project-name.lndo.site

tooling:
    wp:
        service: appserver
        cmd: wp
    npm:
        service: node
        cmd: npm
    node:
        service: node
        cmd: node
    composer:
        service: appserver
        cmd: composer

events:
    pre-stop:
        - echo "Backing up database..."
        - lando wp db export - | gzip > db_backup.sql.gz
        - echo "Database successfully backed up"
